<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
	  <PublishAot>true</PublishAot>
    <ImplicitUsings>enable</ImplicitUsings>
	  <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <Nullable>enable</Nullable>
    <ApplicationIcon>alarm.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="alarm.ico" />
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.1" />
    <PackageReference Include="NAudio" Version="2.2.1" />

	  <PackageReference Include="org.k2fsa.sherpa.onnx" Version="1.12.22" />
    
    <PackageReference Include="Vosk" Version="0.3.38" />
    <PackageReference Include="XT.MNet" Version="1.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Audio.Core\Audio.Core.csproj" />
  </ItemGroup>

</Project>
